name: Build

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: latest
      pushImage:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Set up JDK 13
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '13'
        architecture: x64

    - name: Maven Build
      run: mvn clean install

    - name: Setup Docker Buildx
      run: |
        docker buildx create --name codbex-builder
        docker buildx use codbex-builder

    - name: Build Docker Image
      if: ${{ !inputs.pushImage }}
      run: |
        cd application
        docker buildx build --tag codbex-hades -o type=image --platform=linux/arm64,linux/amd64 .

    - name: Build and Push Docker Image
      if: ${{ inputs.pushImage }}
      run: |
        cd application
        docker login ghcr.io -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
        docker buildx build --push --tag ghcr.io/codbex/codbex-hades:${{ inputs.version }} -o type=image --platform=linux/arm64,linux/amd64 .
