name: Pull Request - Platform

on:
  pull_request:
    branches: 
      - main

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-pull-request.yaml@main
    with:
      application-name: codbex-hades
    secrets: inherit
