name: Release - Platform

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 2.0.0
      snapshot-version:
        description: Snapshot Version
        required: true
        default: 3.0.0-SNAPSHOT

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-release.yaml@main
    with:
      platform-name: codbex-hades
      maven-release: true
      release-version: ${{ inputs.release-version }}
      snapshot-version: ${{ inputs.snapshot-version }}
      docker-release: true
      release-otc-helm-chart: true
      release-content: |
        ## codbex-hades - ${{ inputs.release-version }}
        
        Database Management Platform
        
        ## Deployment
        
        ```
        docker run --name codbex-hades \
        --rm -p 80:80 -p 8081:8081 \
        ghcr.io/codbex/codbex-hades:${{ inputs.release-version }}
        ```
        
        ## Access points:
        
        - [/services/web/ide-database/](http://localhost/services/web/ide-database/) - Database Perspective
    secrets: inherit
